#!/usr/bin/env bash
#
# Bootstraps puppet
#

if which puppet > /dev/null 2>&1; then
  echo "Puppet is already installed."
  exit 0
fi

# Do the initial apt-get update
echo "Initial apt-get update..."
apt-get update >/dev/null


# Install Puppet
echo "Installing Puppet..."
apt-get install -y puppet >/dev/null

# Success
echo "Puppet installed!"
